baseurl = "https://blog.mjamo.com/"
languageCode = "en-us"
title = "James Muranga's Ideas"
MetaDataFormat = "toml"

[pagination]
    pagerSize = 10

[params]
    author = "James Muranga"
    description = "Notes of my day to day encounters as a Software Developer"
    themeColor = "theme-base-08"
    highlightjs = false
[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    category = "categories"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Photos"
    url = "https://glass.photo/ja4mo"